---
title: 'About'
output: md_document
---

## About

Large banking and financial institutions are remarkably complex, but data on their inner workings is difficult to access and analyze in a useful way. In the spirit of greater transparency, this project helps illuminate one aspect of their complexity&mdash;organizational structure&mdash;and its evolution over time. The institutions in question are _bank holding companies_, which are described in greater detail in the Background section.

The underlying data comes from the <a href='https://www.ffiec.gov/nicpubweb/nicweb/nichome.aspx' target='_blank'>National Information Center</a> (NIC) website, where users can query the corporate structure of a holding company as of a particular date. Each company is essentially a "network" of subsidiaries and can therefore be visualized using tools for network analysis.

I made this application with R's <code>shiny</code>, <code>RMarkdown</code>, and <code>networkD3</code> packages and the <code>D3.js</code> JavaScript library by Mike Bostock. Some of the source files are available on <a href='https://github.com/sirallen/nic-structure' target='_blank'>my Github page</a>. If you want to get in touch, please email me at <a href='mailto:allen.sirolly@gmail.com'>allen.sirolly@gmail.com</a>.

